# Creates a draft release
name: Draft Release
on:
  push:
    branches:
      - main

jobs:
  currentVersion:
    name: Check if current version
    runs-on: ubuntu-latest
    outputs:
      isCurrentVersion: ${{ steps.early.conclusion }}
      version: ${{ steps.version.version }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Fetch version
        id: version
        run: |
          VERSION="$(cat VERSION)"
          echo "::set-output name=version::$VERSION"

      - name: Early stop if no new version
        id: early
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EARLY==$([[ $(gh release view --json tagName --jq .tagName) == $VERSION ]] && echo "yes" || echo "no")
          echo "::set-output name=isCurrentVersion::$EARLY"

  releaseDraft:
    name: Update draft
    runs-on: ubuntu-latest
    needs: currentVersion
    if: needs.currentVersion.outputs.isCurrentVersion == 'no'
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Remove old release drafts by using the curl request for the available releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ needs.currentVersion.outputs.version }} \
            --draft \
            --title "${{ needs.currentVersion.outputs.version }}" \
            --generate-notes

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Download Box Phar
        run: wget https://github.com/box-project/box/releases/latest/download/box.phar && chmod 755 box.phar

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Compile Graphlint into Phar
        run: ./box.phar compile

      - name: Upload phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.currentVersion.outputs.version }} build/graphlint