name: Tests

on:
  push:

jobs:
  setup:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Pest on PHP ${{ matrix.php }}
    strategy:
      fail-fast : false
      matrix:
        php: ["8.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Test php code
        run: php vendor/bin/pest --parallel
